### ISSUE TITLE
Can't get correct result on windows platform

### ISSUE THREAD

**Issue by jnoylinc** [YinlinHu/CPM#6]
hi,I build a project to run this code on vs2013, and I use the opencv3.1 and opencv_contrip310.
when I choose a debug version, errors happened
Opencv Error: Assertion failed <i1 < size.p[1]> in cv::Mat::ptr
when I choose a release version, I get a flow image, but it is not right!
Anyone encountered same problem?
Please offer some help~ Thx~

**Comment by YinlinHu** [comment]
I think the reason is that you linked the release version of OpenCV when compiled with debug CPM. There will be some weird problem when linking to OpenCV with the wrong (DEBUG / RELEASE) setting.
